### ISSUE TITLE
Disneyland paris * access denied *

### ISSUE THREAD

**Issue by matounet51** [cubehouse/themeparks#238] opened 2019-10-10 08:35 UTC
Hy!

Since this morning, Disneyland Paris have an denied access:

Error fetching park wait times: 403: "<HTML><HEAD>\n<TITLE>Access Denied</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don't 
have permission to access \"http&#58;&#47;&#47;api&#46;wdpro&#46;disney&#46;go&#46;com&#47;facility&#45;service&#47;theme&#45;parks&#4
7;P1&#59;destination&#61;dlp&#47;wait&#45;times&#63;\" on this server.<P>\nReference&#32;&#35;18&#46;573a3217&#46;1570696333&#46;ae83d
22\n</BODY>\n</HTML>\n"

**Comment by zacharyedwardbull** [comment] 2019-10-10 14:39
Seems that they no longer use the legacy API, and rather than moving to the same couchbase API as other Disney Parks they have created a new endpoint. I've removed the API key used since I'm not sure if it is tied to the app installation or if it is constant for everyone.

```
curl -H 'Host: dlp-wt.wdprapps.disney.com' 
-H 'accept: application/json, text/plain, */*' 
-H 'x-api-key: *REDACTED*' 
-H 'user-agent: okhttp/3.12.1' --compressed 'https://dlp-wt.wdprapps.disney.com/prod/v1/waitTimes'
```

This gives the following response

```javascript
[{
	"entityId": "P1NA07",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "10"
}, {
	"entityId": "P1NA05",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "25"
}, {
	"entityId": "P2YA01",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1NA08",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "15"
}, {
	"entityId": "P1NA09",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1RA04",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1RA05",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1RA06",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "25"
}, {
	"entityId": "P1RA07",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.726+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1RA00",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "75"
}, {
	"entityId": "P1NA02",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "10"
}, {
	"entityId": "P1NA03",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1NA00",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1RA03",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "15"
}, {
	"entityId": "P1NA01",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "30"
}, {
	"entityId": "P1DA13",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "10"
}, {
	"entityId": "P1DA14",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "25"
}, {
	"entityId": "P1NA17",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "75"
}, {
	"entityId": "P1MA05",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1MA06",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "55"
}, {
	"entityId": "P1NA16",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1MA04",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P2ZA01",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P2ZA02",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "50"
}, {
	"entityId": "P2ZA00",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1NA10",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "60"
}, {
	"entityId": "P1NA13",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "DOWN",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "25"
}, {
	"entityId": "P1MA01",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1NA12",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1RA10",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1AA03",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1AA04",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "30"
}, {
	"entityId": "P1AA05",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1AA00",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1AA01",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "5"
}, {
	"entityId": "P1AA02",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1AA08",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "DOWN",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P2XA02",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "10"
}, {
	"entityId": "P2XA01",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P2XA03",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": true,
		"singleRiderWaitMinutes": "40"
	},
	"postedWaitMinutes": "60"
}, {
	"entityId": "P2XA00",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "45"
}, {
	"entityId": "P1DA10",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P1DA08",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": true,
		"singleRiderWaitMinutes": "35"
	},
	"postedWaitMinutes": "60"
}, {
	"entityId": "P1DA09",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "15"
}, {
	"entityId": "P1DA06",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "5"
}, {
	"entityId": "P1DA07",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "30"
}, {
	"entityId": "P1DA04",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "45"
}, {
	"entityId": "P1DA03",
	"type": "Attraction",
	"parkId": "0/P/P1",
	"status": null,
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "0"
}, {
	"entityId": "P2XA09",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": true,
		"singleRiderWaitMinutes": "5"
	},
	"postedWaitMinutes": "30"
}, {
	"entityId": "P2XA06",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": true,
		"singleRiderWaitMinutes": "45"
	},
	"postedWaitMinutes": "55"
}, {
	"entityId": "P2XA05",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "10"
}, {
	"entityId": "P2XA08",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": false,
		"singleRiderWaitMinutes": null
	},
	"postedWaitMinutes": "5"
}, {
	"entityId": "P2XA07",
	"type": "Attraction",
	"parkId": "0/P/P2",
	"status": "OPERATING",
	"responseTimestamp": "2019-10-10T14:28:52.727+0000",
	"singleRider": {
		"isAvailable": true,
		"singleRiderWaitMinutes": "15"
	},
	"postedWaitMinutes": "35"
}]
```

**Comment by hemi1986** [comment] 2019-10-10 19:37
I had the same error on my server and then ran the script locally where everything worked. I redeployed the script on the server (had to update on version to 5.1.20 anyways) and now it works again. maybe the cached api access token was expired? 

the lib gets an token from "https://authorization.go.com/token" (except for disney shanghai) to make further calls and this is cached in the themeparks.db sqlite database (with expire date) which gets created in your root folder when you start using the lib (just had a fast look at the implementation of the disney parks, so possibly im wrong^^). Maybe the token expired earlier for some reason?

atm everything looks fine for me and locally i wasnt able to reproduce the issue for now... maybe it helps to clear this cache and then start your app again?

**Comment by cubehouse** [comment] 2019-10-10 20:27
Started a pull request. Implemented ride times, need to sort out opening hours still to merge

**Comment by cubehouse** [comment] 2019-10-10 21:12
Pushed an implementation of their new API in 5.1.21. Let me know how it goes.

**Comment by LouisForaux** [comment] 2019-10-10 21:27
Hey @cubehouse ! 
Please be careful with the names of the rides, for the moment, is in English.. For a French park ;)

But it's a great work in a short time ! It works !

**Comment by cubehouse** [comment] 2019-10-11 13:12
Sorry, I don't understand your request re: English names?
All parks should return English through this API where possible.

Closing this now, not heard anything from anyone regarding if this is working now for them, but it seems to be working for me.

**Closed by cubehouse** 2019-10-11 13:12 UTC

**Comment by matounet51** [comment] 2019-10-11 14:54
Perfect for me too ! Thanks for reactivity !

**Comment by matounet51** [comment] 2019-10-11 14:56
For english names, last API returns french names. Not the new one. Corrected with PHP for me and it's perfect! 
Http://d-land.fr
